### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-owncloud#5]
I've tried setting up owncloud with a cifs share (freenas). The share is mounted on the docker host with:

```
//serveraddress.net/owncloudshare /media/owncloudshare cifs credentials=/home/username/credentials.txt,iocharset=utf8,uid=1000,gid=1000,sec=ntlm 0 0
```

And the following docker create command:

```
docker create --name=owncloud -v ~/configs/owncloud:/config \
-v /media/owncloud:/data -e PGID=1000 -e PUID=1000 \
-p 443:443 lsiodev/owncloud
```

Setup runs as expected, but the webinterface shows the following error:

```
Data directory (/data) is readable by other users
Please change the permissions to 0770 so that the directory cannot be listed by other users
```

Any idea what's causing this problem?

**Comment by zaggash** [comment]
Hello,

What's the permissions on /media/owncloud ?

Coud you confirm your share and docker arguments : 
/media/owncloudshare
/media/owncloud

**Comment by zaggash** [comment]
Anyway you can try to mount with this option  dir_mode=0770

**Comment by ghost** [comment]
> Coud you confirm your share and docker arguments

Sorry, didn't anonymise it correctly, docker create command should be:

```
docker create --name=owncloud -v ~/configs/owncloud:/config \
-v /media/owncloudshare:/data -e PGID=1000 -e PUID=1000 \
-p 443:443 lsiodev/owncloud
```

> Anyway you can try to mount with this option dir_mode=0770

I did, but it considers that an invalid option for a cifs share. I think a solution might be to use a unix share, as that can be configured with the right permissions (hopefully).

**Comment by zaggash** [comment]
The problem is you permissions on the data folder which is 777.

**Comment by ghost** [comment]
> The problem is you permissions on the data folder which is 777.

Yeah I know, problem is, freenas won't allow me to use `chmod` to modify this on the share once it's mounted. And for a windows share I can't set it manually in freenas, only for unix shares. I'll see whether that fixes it.

**Comment by ghost** [comment]
So using an nfs share with 0770 permissions fixed it. Not a bug with this docker, but more an owncloud thing.
