### ISSUE TITLE
Update via webui?

### ISSUE THREAD

**Issue by skidelo** [linuxserver/docker-owncloud#7]
Yes, I know this container is in beta.  That said...
The documentation says to update owncloud via the webUI.  However, the "Updater" plugin in the webUI thinks I am up-to-date at 9.0.4.  At the time of this writing, OC is at 9.1.1.

Seems like the Updater isn't properly detecting whether or not there is an update available.

**Comment by j0nnymoe** [comment]
In terms of our ourcloud docker, we will be dropping this one in favour of nextcloud which our current docker is in development.

https://hub.docker.com/r/lsiodev/nextcloud/
